<label for="project" class="my-2">Project *</label>

<div class="form-group my-1">
    <?php foreach (\App\Service\Projects\Projects::getAll(current_account()) as $projectSlug => $projectTitle): ?>
        <input type="radio" class="btn-check" name="project" value="<?=$projectSlug ;?>" id="<?=$projectSlug ;?>" autocomplete="off">
        <label class="btn btn-secondary mb-2 bg-<?=$projectSlug; ?>" for="<?=$projectSlug ;?>">
            <?=$projectTitle; ?>
        </label>
    <?php endforeach; ?>
</div>
