<?php
namespace App\Service\Images\RipplePunks;

use App\Service\Images\BaseImage;
use App\Service\Projects\Projects;
use App\Service\Traits\HasOptions;

class RipplePunksQuartetSet extends BaseImage
{
    use HasOptions;

    protected string $project = Projects::RIPPLE_PUNKS;

    protected string $name = 'RipplePunks Quartet Set';

    protected string $description = 'This image type gives a full quartet set for the chosen attribute';

    public function __construct()
    {
        $this->options = [
            "Male - Eye Patch",
            "Female - Vape",
            "Female - Tassle Hat",
            "Female - Orange Side",
            "Female - Straight Hair Dark",
            "Alien - ",
            "Male - Small Shades",
            "Male - Clown Eyes Green",
            "Male - Muttonchops",
            "Male - Regular Shades",
            "Female - Hot Ripple Lipstick",
            "Female - Horned Rim Glasses",
            "Female - Straight Hair Light",
            "Female - Ripple Mohawk",
            "Zombie - Messy Hair",
            "Male - Mustache",
            "Male - Shadow Beard",
            "Male - Smile",
            "Male - Clown Nose",
            "Female - Headband",
            "Male - Police Cap",
            "Male - Medical Mask",
            "Female - Green Eye Shadow",
            "Female - Mohawk Dark",
            "Male - Clown Eyes Blue",
            "Male - Hoodie",
            "Zombie - Luxurious Beard",
            "Male - Gold Chain",
            "Female - Wild Hair",
            "Female - Messy Hair",
            "Female - Blue Eye Shadow",
            "Zombie - Horned Rim Glasses",
            "Female - Silver Chain",
            "Zombie - Stringy Hair",
            "Male - Cowboy Hat",
            "Male - Big Beard",
            "Female - Eye Patch",
            "Male - Chinstrap",
            "Male - Normal Beard",
            "Female - Classic Shades",
            "Female - Half Shaved",
            "Female - Pigtails",
            "Female - Bandana",
            "Female - Wild White Hair",
            "Female - Purple Lipstick",
            "Female - VR",
            "Male - Top Hat",
            "Female - Pink With Hat",
            "Female - Clown Eyes Blue",
            "Male - Normal Beard Black",
            "Male - Silver Chain",
            "Female - Purple Eye Shadow",
            "Male - Do-rag",
            "Female - Nerd Glasses",
            "Female - Pilot Helmet",
            "Female - Rosy Cheeks",
            "Male - Shaved Head",
            "Female - Clown Eyes Green",
            "Female - Gold Chain",
            "Female - Pipe",
            "Male - Cap",
            "Female - Spots",
            "Male - Goat",
            "Female - Clown Nose",
            "Female - Tiara",
            "Female - Black Lipstick",
            "Female - Stringy Hair",
            "Male - Wild Hair",
            "Female - Big Shades",
            "Female - 3D Glasses",
            "Male - Stringy Hair",
            "Male - Buck Teeth",
            "Male - Front Beard Dark",
            "Male - Messy Hair",
            "Male - Beanie",
            "Male - Bandana",
            "Female - Medical Mask",
            "Male - Headband",
            "Female - Clown Hair Green",
            "Male - Cigarette",
            "Male - Fedora",
            "Male - Luxurious Beard",
            "Female - Cap",
            "Male - Mohawk Thin",
            "Zombie - Peak Spike",
            "Male - Vampire Hair",
            "Male - Frumpy Hair",
            "Male - Mohawk Dark",
            "Male - Rosy Cheeks",
            "Female - Mohawk",
            "Male - Peak Spike",
            "Male - Mohawk",
            "Male - Ripple Hair",
            "Male - Handlebars",
            "Male - Crazy Hair",
            "Female - Dark Hair",
            "Male - Mole",
            "Male - Big Shades",
            "Female - Wild Ripple",
            "Female - Mohawk Thin",
            "Male - Horned Rim Glasses",
            "Male - Eye Mask",
            "Male - Frown",
            "Male - Spots",
            "Female - Mole",
            "Female - Knitted Cap",
            "Female - Ripple Short",
            "Male - Knitted Cap",
            "Male - Pipe",
            "Female - Ripple Bob",
            "Male - 3D Glasses",
            "Female - Frumpy Hair",
            "Male - Front Beard",
            "Male - Clown Hair Green",
            "Male - VR",
            "Female - Eye Mask",
            "Male - Classic Shades",
            "Female - Straight Hair Blue",
            "Female - Crazy Hair",
            "Zombie - Crazy Hair",
            "Female - Welding Goggles",
            "Female - Cigarette",
            "Male - Cap Forward",
            "Male - Vape",
            "Female - Regular Shades",
            "Male - Nerd Glasses",
            "Female - Choker",
            "Zombie - Cigarette"
        ];
    }
}
