<?php
/**
 * @var $image \App\Models\Image
 */
?>

<div class="container-fluid">
    <div class="row justify-content-center">

        <h2>
            <a href="<?=env('URL_HYPEOMATIC'); ?>/<?=$image->getProjectNeatUrlSlug(); ?>">
                <?=$image->getProjectName(); ?>
            </a>
        </h2>
        <h3><?=$image->getTitle(); ?></h3>

        <div class="col col-lg-4">
            <?php if ($image->canRedo()): ?>
                <a href="<?=env('URL_HYPEOMATIC'); ?>/redo/<?=$image->uuid; ?>" class="btn btn-primary redo-button">Redo</a>
            <?php endif; ?>
            <div class="card">
                <div class="card-body">
                    <img class="img-fluid" src="<?=$image->url; ?>" />
                </div>
            </div>
            <?php if ($image->canRedo()): ?>
                <a href="<?=env('URL_HYPEOMATIC'); ?>/redo/<?=$image->uuid; ?>" class="btn btn-primary redo-button">Redo</a>
            <?php endif; ?>
        </div>
    </div>
</div>
