<?php
/**
 * @var $image \App\Models\Image
 */
?>

<div class="container-fluid">
    <div class="row justify-content-center">

        <h2><?=$image->textImage; ?></h2>

        <div class="col col-lg-4">
            <div class="card">
                <form id="posts-form" method="post" action="">
                    <div class="card-body">
                        <img class="img-fluid" src="<?=$image->url; ?>" />
                    </div>
                </form>
            </div>
            <?php if ($image->canRedo()): ?>
                <button type="submit" class="btn btn-primary">Redo</button>
            <?php endif; ?>
        </div>
    </div>
</div>
