<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="HasMints.com">

    <title><?=$htmlTitle; ?></title>

    <link href="<?=env('URL'); ?>/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?=env('URL'); ?>/assets/css/main.css?t=<?=date('dmYHi'); ?>" rel="stylesheet">
</head>

<body data-url="<?=env('URL'); ?>">
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="<?=env('URL'); ?>">X Easy Post (<?=$actualPostsLast24Hours; ?>)</a>
            <?php if ($isLoggedIn): ?>
                <div class="dropdown">
                    <a class="navbar-item dropdown-toggle" href="#" role="button" id="userDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                        <strong>
                            <?=current_account(); ?>
                        </strong>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="userDropdown">
                        <?php foreach (get_all_accounts() as $account): ?>
                            <?php if (current_account() !== $account): ?>
                                <li><a class="dropdown-item" href="<?= env('URL'); ?>/account/<?=$account; ?>"><?=$account; ?></a></li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <a class="navbar-item" href="<?=env('URL'); ?>/logout">Logout</a>
            <?php endif; ?>
        </div>
    </nav>

    <main>

<!--        --><?php //if ($alert): ?>
<!--            <div class="container alert-container">-->
<!--                <div class="alert alert---><?php //=$alert['type']; ?><!-- mt-5 text-center" role="alert">-->
<!--                    --><?php //=$alert['message']; ?>
<!--                </div>-->
<!--            </div>-->
<!--        --><?php //endif; ?>

        <?=$content; ?>
    </main>

    <footer class="py-4">
        <p class="text-center">Built by <a target="_blank" href="https://hasmints.com/">HasMints</a>.</p>
    </footer>

    <script type="text/javascript" src="<?=env('URL'); ?>/assets/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="<?=env('URL'); ?>/assets/js/main.js?t=<?=date('dmYHi'); ?>"></script>
</body>

</html>
