<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="HasMints.com">

    <title><?=$htmlTitle; ?></title>

    <link href="<?=env('URL'); ?>/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?=env('URL'); ?>/assets/css/main.css?t=<?=date('dmYHi'); ?>" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="<?=env('URL'); ?>">X Easy Post</a>
        </div>
    </nav>

    <main>

        <?php if ($alert): ?>
            <div class="container">
                <div class="alert alert-<?=$alert['type']; ?> mt-5 text-center" role="alert">
                    <?=$alert['message']; ?>
                </div>
            </div>
        <?php endif; ?>

        <?=$content; ?>
    </main>

    <footer class="py-4">
        <p>Built by <a target="_blank" href="https://hasmints.com/">HasMints</a>.</p>
    </footer>

    <script type="text/javascript" src="<?=env('URL'); ?>/assets/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="<?=env('URL'); ?>/assets/js/main.js"></script>
</body>

</html>
