<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="HasMints.com">

    <title><?=$htmlTitle; ?></title>

    <link href="<?=env('URL_HYPEOMATIC'); ?>/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?=env('URL_HYPEOMATIC'); ?>/assets/css/hypeomatic.css?t=<?=date('dmYHi'); ?>" rel="stylesheet">

    <link rel="apple-touch-icon" sizes="180x180" href="<?=env('URL_HYPEOMATIC'); ?>/assets/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="<?=env('URL_HYPEOMATIC'); ?>/assets/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="<?=env('URL_HYPEOMATIC'); ?>/assets/favicon/favicon-16x16.png">
    <link rel="manifest" href="<?=env('URL_HYPEOMATIC'); ?>/assets/favicon/site.webmanifest">
</head>

<body data-url="<?=env('URL_HYPEOMATIC'); ?>">

<header>
    <h1>
        <a href="<?=env('URL_HYPEOMATIC'); ?>">
            Hypeomatic
        </a>
    </h1>
</header>

<main>

    <?=$content; ?>

</main>


<div class="container-fluid container-color-1">
    <div class="row justify-content-center">
        <div class="col col-12 col-lg-7">
            <p class="disclaimer py-4">
                <strong>Disclaimer</strong>:
                Please note that the images generated using this tool are solely based on the text input provided by users.
                We only provide the tool to facilitate the creation of these images and do not have any control over the content or results produced.
                The text therein reflect the input and creativity of individual users and do not represent our views or opinions.
                Users are responsible for ensuring that their input complies with applicable laws and guidelines.
                We disclaim any liability for the content generated through this tool.
            </p>
        </div>
    </div>
</div>

<footer>
    Built by <a target="_blank" href="https://hasmints.com/">HasMints</a> ~ &copy; <?=date('Y'); ?>
</footer>

<br />

<span class="sweat">
    💦
</span>

<script type="text/javascript" src="<?=env('URL_HYPEOMATIC'); ?>/assets/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="<?=env('URL_HYPEOMATIC'); ?>/assets/js/hypeomatic.js?t=<?=date('dmYHi'); ?>"></script>
</body>

</html>
