<?php
/**
 * @var $formHelper \App\Service\Form\FormHelper
 */
?>

<?php if ($formHelper->hasImage): ?>
    <?php include ('templates/views/website/partial/form-elements/image.phtml'); ?>
<?php endif; ?>

<?php if ($formHelper->hasImageText): ?>
    <?php include ('templates/views/website/partial/form-elements/text-image.phtml'); ?>
<?php endif; ?>

<?php if ($formHelper->nftIdRange): ?>
    <?php include ('templates/views/website/partial/form-elements/nft-id.phtml'); ?>
<?php endif; ?>

<?php if ($formHelper->options): ?>
    <?php include ('templates/views/website/partial/form-elements/type.phtml'); ?>
<?php endif; ?>

<?php if ($formHelper->hasImage && $formHelper->selectedImage): ?>
    <button type="submit" class="btn btn-primary mt-4">
        <?php if (is_hypeomatic_website()): ?>
            Hype me Up!
        <?php else: ?>
            Schedule Post
        <?php endif; ?>
    </button>
<?php endif; ?>
