<?php
/**
 * @var $image \App\Models\Image
 */
?>

<a class="card" href="<?=env('URL_HYPEOMATIC'); ?>/<?=$image->getProjectNeatUrlSlug(); ?>">
    <?php if (!$selectedProjectSlug): ?>
        <div class="card-header">
            <?=$image->getProjectName(); ?>
        </div>
    <?php endif; ?>
    <div class="card-body">
        <img class="img-fluid" src="<?=$image->url; ?>" />
    </div>
</a>

