<?php
/**
 * @var $image \App\Models\Image
 */
?>

<div class="card">
    <?php if (!$selectedProjectSlug): ?>
        <div class="card-header">
            <a href="<?=env('URL_HYPEOMATIC'); ?>/<?=$image->getProjectNeatUrlSlug(); ?>">
                <?=$image->getProjectName(); ?>
            </a>
        </div>
    <?php endif; ?>
    <div class="card-body">
        <a href="<?=$image->getUrl(); ?>">
            <img class="img-fluid" src="<?=$image->url; ?>" />
        </a>
    </div>
</div>

