<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col col-12">
            <p>
                <?=$countPostsInLastPeriod; ?>
                post<?=$countPostsInLastPeriod > 1 ? 's' : ''; ?>
                in the last 24 hours, also
                <strong>
                    there <?=$countScheduledPosts > 1 ? 'are' : 'is'; ?> <?=$countScheduledPosts; ?> scheduled post<?=$countScheduledPosts > 1 ? 's' : ''; ?>
                </strong>
                <?php if ($countScheduledPosts >= 1): ?>
                    <small>
                        (until <?=$lastPostScheduledForDate->format('d/m H:00'); ?>)
                    </small>
                <?php endif ?>
            </p>
        </div>
        <div class="col col-12">
            <div class="progress">
                <?php foreach ($shilledPerProject as $project => $totalShilledPercentage): ?>
                    <div
                        class="progress-bar bg-<?=strtolower($project); ?>"
                        role="progressbar"
                        style="width: <?=$totalShilledPercentage; ?>%"
                        aria-valuenow="<?=$totalShilledPercentage; ?>>"
                        aria-valuemin="0"
                        aria-valuemax="100"
                    ></div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="col col-12 col-sm-4 mt-4">
            <div class="card">
                <div class="card-body">
                    <form id="register" method="post" action="">
                        <div class="form-group my-3">
                            <label for="project_name" class="my-2">Text *</label>
                            <textarea
                                name="text"
                                class="form-control <?=$formErrors && isset($formErrors['text']) ? 'is-invalid' : ''; ?>"
                                id="text"
                                rows="5"
                            ><?=$formValidatedValues && isset($formValidatedValues['text']) ? $formValidatedValues['text'] : ''; ?></textarea>
                            <?=parse_form_errors('text', $formErrors); ?>
                        </div>
                        <div class="form-group my-3">
                            <label for="image" class="my-2">Image (optional)</label>
                            <select
                                name="image"
                                class="
                                    custom-select
                                    form-control
                                    <?=$formErrors && isset($formErrors['image']) ? 'is-invalid' : ''; ?>
                                "
                                id="image"
                            >
                                <option></option>
                                <?php foreach(\App\FormFieldValidator\Image::getOptions() as $option) : ?>
                                    <option
                                        <?php if (in_array($option, [
                                            'LoadingPunks NFT',
                                            'LoadingPunks Pixel Count',
                                            'PipingPunks NFT',
                                            'PipingPunks Moving',
                                            'RipplePunks',
                                            'RipplePunks QR',
                                        ])): ?>
                                            class="option-crypto-punk"
                                        <?php endif; ?>
                                        value="<?=flatten_string($option); ?>"
                                        <?=$formValidatedValues && isset($formValidatedValues['image']) && ($formValidatedValues['image'] === flatten_string($option)) ? 'selected' : ''; ?>
                                    >
                                        <?=$option; ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                            <?=parse_form_errors('image', $formErrors); ?>
                        </div>
                        <div class="form-group my-3">
                            <label for="email" class="my-2">Post ID or URL (optional)</label>
                            <input
                                type="text"
                                name="post_id"
                                class="form-control <?=$formErrors && isset($formErrors['post_id']) ? 'is-invalid' : ''; ?>"
                                value="<?=$formValidatedValues && isset($formValidatedValues['post_id']) ? $formValidatedValues['post_id'] : ''; ?>"
                                id="post_id"
                            />
                            <?=parse_form_errors('post_id', $formErrors); ?>
                        </div>
                        <div class="form-group my-3">
                            <label for="nft_id" class="my-2">NFT ID (optional)</label>
                            <input
                                type="text"
                                name="nft_id"
                                class="
                                    form-control
                                    <?=$formErrors && isset($formErrors['nft_id']) ? 'is-invalid' : ''; ?>
                                "
                                value="<?=$formValidatedValues && isset($formValidatedValues['nft_id']) ? $formValidatedValues['nft_id'] : ''; ?>"
                                id="nft_id"
                            />
                            <?=parse_form_errors('nft_id', $formErrors); ?>
                        </div>
                        <div class="form-group my-3">
                            <label for="project_name" class="my-2">Type (optional)</label>
                            <select
                                name="type"
                                class="
                                    custom-select
                                    form-control
                                    <?=$formErrors && isset($formErrors['type']) ? 'is-invalid' : ''; ?>
                                "
                                id="type"
                            >
                                <option></option>
                                <?php foreach(\App\FormFieldValidator\Type::getTypesCryptoPunks() as $type) : ?>
                                    <option
                                        class="type-crypto-punk hide"
                                        value="<?=$type; ?>"
                                        <?=$formValidatedValues && isset($formValidatedValues['type']) && ($formValidatedValues['type'] === $type) ? 'selected' : ''; ?>
                                    >
                                        <?=$type; ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                            <?=parse_form_errors('type', $formErrors); ?>
                        </div>
                        <button type="submit" class="btn btn-primary">Post on X</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col col-12 col-sm-8 mt-4">
            <div class="table-responsive">
                <table class="table">
                    <?php foreach ($lastPosts as $post): /* @var $post \App\Models\Post */ ?>
                        <tr class="<?=!isset($post->success) ? 'scheduled' : ''; ?>" title="<?=json_encode($post->result); ?>">
                            <td><?=$post->postId ? 'R' : 'P'; ?></td>
                            <?php if (isset($post->success)): ?>
                                <td><?=$post->success ? '<a target="_blank" href="https://x.com/HasMints/status/' . $post->readableResult . '">Y</a>' : 'N'; ?></td>
                            <?php else: ?>
                                <td>-</td>
                            <?php endif; ?>
                            <td class="w-100">
                                <?php if (isset($post->text)): ?>
                                    <?=nl2br($post->text); ?>
                                <?php endif; ?>
                                <?php if (isset($post->image)): ?>
                                    <?php if (isset($post->text)): ?>
                                        <br />
                                    <?php endif; ?>
                                    <a target="_blank" href="<?=$post->image; ?>">
                                        <img class="w-50" src="<?=$post->image; ?>" />
                                    </a>
                                <?php endif; ?>
                                <?php if (isset($post->success) && !$post->success): ?>
                                    <?=$post->readableResult; ?>
                                <?php endif; ?>
                            </td>
                            <td style="min-width: 200px;" class="text-end">
                                <?=$post->postedAt ?: 'Scheduled'; ?>
                                <?php if (!$post->postedAt): ?>
                                    <br />
                                    <small>
                                        <a href="/delete-scheduled-post/<?=$post->id; ?>">
                                            (delete)
                                        </a>
                                    </small>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    document.getElementById('image').addEventListener('change', function() {
        const selectedOption = this.options[this.selectedIndex];
        const typeOptions = document.querySelectorAll('select#type option.type-crypto-punk');

        if (selectedOption.classList.contains('option-crypto-punk')) {
            typeOptions.forEach(option => {
                option.classList.remove('hide');
                option.removeAttribute('disabled')
            });
        } else {
            typeOptions.forEach(option => {
                option.classList.add('hide');
                option.setAttribute('disabled', 'disabled')
            });
        }
    });
</script>