<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col col-12">
            <p>
                <?=$countPostsInLastPeriod; ?>
                post<?=$countPostsInLastPeriod > 1 ? 's' : ''; ?>
                in the last 24 hours, also
                <strong>
                    there <?=$countScheduledPosts > 1 ? 'are' : 'is'; ?> <?=$countScheduledPosts; ?> scheduled post<?=$countScheduledPosts > 1 ? 's' : ''; ?>
                </strong>
                <?php if ($countScheduledPosts >= 1): ?>
                    <small>
                        (until <?=$lastPostScheduledForDate->format('d/m H:00'); ?>)
                    </small>
                <?php endif ?>
            </p>
        </div>
        <div class="col col-12">
            <div class="progress">
                <?php foreach ($shilledPerProject as $project => $totalShilledPercentage): ?>
                    <div
                        class="progress-bar bg-<?=strtolower($project); ?>"
                        role="progressbar"
                        style="width: <?=$totalShilledPercentage; ?>%"
                        aria-valuenow="<?=$totalShilledPercentage; ?>>"
                        aria-valuemin="0"
                        aria-valuemax="100"
                    ></div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="col col-12 col-sm-4 mt-4">
            <div class="card">
                <div class="card-body">
                    <form id="register" method="post" action="">
                        <div class="form-group my-3">
                            <label for="project_name" class="my-2">Text *</label>
                            <textarea
                                name="text"
                                class="form-control <?=$formErrors && isset($formErrors['text']) ? 'is-invalid' : ''; ?>"
                                id="text"
                                rows="5"
                            ><?=$formValidatedValues && isset($formValidatedValues['text']) ? $formValidatedValues['text'] : ''; ?></textarea>
                            <?=parse_form_errors('text', $formErrors); ?>
                        </div>
                        <div class="form-group my-3">
                            <label for="image" class="my-2">Image (optional)</label>
                            <select
                                name="image"
                                class="
                                    custom-select
                                    form-control
                                    <?=$formErrors && isset($formErrors['image']) ? 'is-invalid' : ''; ?>
                                "
                                id="image"
                            >
                                <option></option>
                                <?php foreach(\App\FormFieldValidator\Image::getOptions() as $option) : ?>
                                    <option
                                        <?php if (in_array($option, [
                                            'LoadingPunks NFT',
                                            'LoadingPunks Pixel Count',
                                            'PipingPunks NFT',
                                            'PipingPunks Moving',
                                            'RipplePunks',
                                            'RipplePunks QR',
                                        ])): ?>
                                            class="option-crypto-punk"
                                        <?php endif; ?>
                                        value="<?=flatten_string($option); ?>"
                                        <?=$formValidatedValues && isset($formValidatedValues['image']) && ($formValidatedValues['image'] === flatten_string($option)) ? 'selected' : ''; ?>
                                    >
                                        <?=$option; ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                            <?=parse_form_errors('image', $formErrors); ?>
                        </div>
                        <div class="form-group my-3">
                            <label for="email" class="my-2">Post ID or URL (optional)</label>
                            <input
                                type="text"
                                name="post_id"
                                class="form-control <?=$formErrors && isset($formErrors['post_id']) ? 'is-invalid' : ''; ?>"
                                value="<?=$formValidatedValues && isset($formValidatedValues['post_id']) ? $formValidatedValues['post_id'] : ''; ?>"
                                id="post_id"
                            />
                            <?=parse_form_errors('post_id', $formErrors); ?>
                        </div>
                        <div class="form-group my-3">
                            <label for="nft_id" class="my-2">NFT ID (optional)</label>
                            <input
                                type="text"
                                name="nft_id"
                                class="
                                    form-control
                                    <?=$formErrors && isset($formErrors['nft_id']) ? 'is-invalid' : ''; ?>
                                "
                                value="<?=$formValidatedValues && isset($formValidatedValues['nft_id']) ? $formValidatedValues['nft_id'] : ''; ?>"
                                id="nft_id"
                            />
                            <?=parse_form_errors('nft_id', $formErrors); ?>
                        </div>
                        <div class="form-group my-3">
                            <label for="project_name" class="my-2">Type (optional)</label>
                            <select
                                name="type"
                                class="
                                    custom-select
                                    form-control
                                    <?=$formErrors && isset($formErrors['type']) ? 'is-invalid' : ''; ?>
                                "
                                id="type"
                            >
                                <option></option>
                                <?php foreach(\App\FormFieldValidator\Type::getTypesCryptoPunks() as $type) : ?>
                                    <option
                                        class="type-crypto-punk hide"
                                        value="<?=$type; ?>"
                                        <?=$formValidatedValues && isset($formValidatedValues['type']) && ($formValidatedValues['type'] === $type) ? 'selected' : ''; ?>
                                    >
                                        <?=$type; ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                            <?=parse_form_errors('type', $formErrors); ?>
                        </div>
                        <button type="submit" class="btn btn-primary">Post on X</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col col-12 col-sm-8 mt-4">
            <ul class="nav nav-tabs" id="tabs" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="replies-tab" data-bs-toggle="tab" data-bs-target="#replies" type="button" role="tab" aria-controls="replies" aria-selected="true">
                        Replies (<?=count($lastPostsReplies); ?>)
                    </button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="posts-tab" data-bs-toggle="tab" data-bs-target="#posts" type="button" role="tab" aria-controls="posts" aria-selected="true">
                        Posts (<?=count($lastPostsPosted); ?>)
                    </button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="scheduled-tab" data-bs-toggle="tab" data-bs-target="#scheduled" type="button" role="tab" aria-controls="scheduled" aria-selected="false">
                        Scheduled (<?=count($lastPostsScheduled); ?>)
                    </button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="failed-tab" data-bs-toggle="tab" data-bs-target="#failed" type="button" role="tab" aria-controls="failed" aria-selected="false">
                        Failed (<?=count($lastPostsFailed); ?>)
                    </button>
                </li>
            </ul>
            <div class="tab-content" id="tab-contents">
                <div class="tab-pane fade show active" id="replies" role="tabpanel" aria-labelledby="replies-tab">
                    <?php $posts = $lastPostsReplies; ?>
                    <?php include ROOT . "/templates/views/website/partial/render-posts.phtml"; ?>
                </div>
                <div class="tab-pane fade" id="posts" role="tabpanel" aria-labelledby="posts-tab">
                    <?php $posts = $lastPostsPosted; ?>
                    <?php include ROOT . "/templates/views/website/partial/render-posts.phtml"; ?>
                </div>
                <div class="tab-pane fade" id="scheduled" role="tabpanel" aria-labelledby="scheduled-tab">
                    <?php $posts = $lastPostsScheduled; ?>
                    <?php include ROOT . "/templates/views/website/partial/render-posts.phtml"; ?>
                </div>
                <div class="tab-pane fade" id="failed" role="tabpanel" aria-labelledby="failed-tab">
                    <?php $posts = $lastPostsFailed; ?>
                    <?php include ROOT . "/templates/views/website/partial/render-posts.phtml"; ?>
                </div>
            </div>


        </div>
    </div>
</div>
