<div class="row row-posts">
    <?php foreach ($posts as $post): /* @var $post \App\Models\Post */ ?>
        <div class="col col-12 col-lg-4">
            <div class="card">
                <div class="card-header">
                    <strong>
                        <?php if ($post->postId): ?>
                            Reply
                        <?php else: ?>
                            Direct Post
                        <?php endif; ?>
                    </strong>
                    <br />

                    <?php if ($post->postedAt): ?>
                        <a target="_blank" href="https://x.com/HasMints/status/<?=$post->readableResult; ?>">
                            <?=$post->postedAt->format('Y-m-d H:i'); ?>
                        </a>
                    <?php else: ?>
                        <?php if (isset($post->success)): ?>
                            <?php if (!$post->success): ?>
                                Failed
                                <br />
                                <strong class="text-danger"><?=$post->readableResult; ?></strong>
                            <?php endif; ?>
                        <?php else: ?>
                            Scheduled
                        <?php endif; ?>
                    <?php endif; ?>

                </div>
                <div class="card-body">
                    <?php if ($post->image): ?>
                        <a target="_blank" href="<?=$post->image; ?>">
                            <img class="w-100" src="<?=$post->image; ?>" />
                        </a>
                    <?php endif; ?>
                </div>
                <div class="card-body">
                    <?php if (isset($post->text)): ?>
                        <?=nl2br($post->text); ?>
                    <?php endif; ?>
                </div>
                <div class="card-footer">
                    <a class="btn btn-primary mb-1" href="/delete-scheduled-post/<?=$post->id; ?>">
                        Delete
                    </a>
                    <?php if (!$post->postedAt): ?>
                        <?php if (isset($post->success) && !$post->success): ?>
                            <a class="btn btn-primary mb-1" href="/retry-post/<?=$post->id; ?>">
                                Retry
                            </a>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($post->image): ?>
                        <a class="btn btn-primary mb-1" href="/redo-image/<?=$post->id; ?>">
                            Redo Image
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
