<div class="table-responsive">
    <table class="table">
        <?php foreach ($posts as $post): /* @var $post \App\Models\Post */ ?>
            <tr class="<?=!isset($post->success) ? 'scheduled' : ''; ?>" title="<?=json_encode($post->result); ?>">
                <td><?=$post->postId ? 'R' : 'P'; ?></td>
                <?php if (isset($post->success)): ?>
                    <td><?=$post->success ? '<a target="_blank" href="https://x.com/HasMints/status/' . $post->readableResult . '">Y</a>' : 'N'; ?></td>
                <?php else: ?>
                    <td>-</td>
                <?php endif; ?>
                <td class="w-100">
                    <?php if (isset($post->text)): ?>
                        <?=nl2br($post->text); ?>
                    <?php endif; ?>
                    <?php if (isset($post->image)): ?>
                        <?php if (isset($post->text)): ?>
                            <br />
                        <?php endif; ?>
                        <a target="_blank" href="<?=$post->image; ?>">
                            <img class="w-50" src="<?=$post->image; ?>" />
                        </a>
                    <?php endif; ?>
                    <?php if (isset($post->success) && !$post->success): ?>
                        <br />
                        <strong class="text-danger"><?=$post->readableResult; ?></strong>
                    <?php endif; ?>
                </td>
                <td style="min-width: 200px;" class="text-end">
                    <?=$post->postedAt ?: 'Scheduled'; ?>
                    <br />
                    <small>
                        <a href="/delete-scheduled-post/<?=$post->id; ?>">
                            (delete)
                        </a>
                        <?php if (isset($post->success) && !$post->success): ?>
                            <a href="/retry-post/<?=$post->id; ?>">
                                (retry)
                            </a>
                        <?php endif; ?>
                    </small>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
