<?php
/**
 * @var $formHelper \App\Service\Form\FormHelper
 */
?>

<div class="form-group my-1">
    <label for="nft_id" class="my-2">NFT ID</label>
    <small>
        <?php if ($nftIdRangePlaceholder = $formHelper->nftIdPlaceholder): ?>
            (<?=$nftIdRangePlaceholder; ?>)
        <?php else: ?>
            (<?=$formHelper->nftIdRange[0]; ?> - <?=$formHelper->nftIdRange[(count($formHelper->nftIdRange) - 1)]; ?>)
        <?php endif; ?>
    </small>
    <input
        type="text"
        name="nft_id"
        class="form-control"
        id="nft_id"
    />
</div>
